name: Deploy to Test

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Test
    environment: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Replace iap-config.json with test config
        run: cp public/config/iap-config.test.json public/iap-config.json

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
